apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapplication" . }}-config
data:
  APP_NAME: "{{ .Values.config.APP_NAME }}"
  APP_ENV: "{{ .Values.config.APP_ENV }}"
  LOG_LEVEL: "{{ .Values.config.LOG_LEVEL }}"
